name: CEC MQTT
mqtt:
  host: localhost
  port: 8883
  username:
  password:
  topic_subscribe_prefix: cec/set
  topic_publish_prefix: cec/status
cec:
  id: 1
  port:
  devices: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
